# ModernShop plugin by Syrows.
# Version: 0.0.1
#
# How to contact me ?
# - Mail: syrows.development@gmail.com
# - Twitter: Syr0ws
# - Discord: Syrows#6297

##########################################################
###                 GENERAL SETTINGS                   ###
##########################################################

# This section allows you to configure groups with specific settings. To add a group to a player, use the
# following permission: modernshop.group.[groupname].
#
# Shop limits is used to define max amount of shops a player can have.
# If you want to allow a player to have an unlimited amount of shops, use the permission 'modernshop.limit.bypass'.
# These limits only involve player shops. Default limit value is fixed by the 'default' group.
# In case of error in the configuration, default limit will be 1.
#
# Shop priority is used to define the order in which shops will appears in the shop menu.
# Here are all the available priorities: ADMIN, EXTREME, VERY_HIGH, HIGH, MEDIUM, NORMAL.
# Default priority is fixed by the 'default' group.
# Warning: ADMIN priority should be used only for admin shops.
shop-groups:
  mvp:
    limit: 15
    priority: VERY_HIGH
  vip:
    limit: 10
    priority: HIGH
  default:
    limit: 5
    priority: NORMAL

# This section is used to configure the lines of text appearing on a shop sign after its creation.
# Note: The line with index 0 corresponds to the first line on the sign.
shop-signs:
  # Lines of text which will be set on the sign of an admin shop.
  admin:
    0: "&8&m--------------------"
    1: "&b&lAdminShop"
    2: ""
    3: "&8&m--------------------"
  # Lines of text which will appear on the sign of a player shop.
  # You can use the place holder %owner_name% to display the name of the shop owner.
  player:
    0: "&8&m--------------------"
    1: "&b&lShop"
    2: "&b&l%owner_name%"
    3: "&8&m--------------------"

teleportation:
  cooldown: 5
  cancel-message: "&7>> &cVous avez bougé. Téléportation annulée."
  cooldown-message: "&2>> &rTéléportation dans &a%time% secondes&r."

enable-logger: true

##########################################################
###                     COMMANDS                       ###
##########################################################

# This section contains all the messages of the 'shops' command.
shops-command:
  # The usage of the command.
  usage:
    # The text of the usage.
    text: "&a/shops &rpour ouvrir le menu de shops."
    # A text which appears when the message is hovered.
    show-text: "&bClique pour exécuter"
    # The background color of the usage. Does not affect other specified colors.
    # Click on this link to see all the available colors: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
    color: "WHITE"
  # Message sent when the message is executed by console.
  not-a-player: "You must be a player to use this command !"
  # Message sent when a player executes the command but he doesn't have the permission 'modernshop.commands.shops'.
  no-permission: "&7>> &cVous n'avez pas la permission d'utiliser cette commande."
  # Message sent when the command has been executed successfully to informs player that the shop menu will be displayed.
  message: "&2>> &rOuverture &rdu menu de &ashops&r."

# This section contains all the messages of the 'modernshop' command.
modernshop-command:
  # The usage of the command.
  usage:
    # The text of the usage.
    text: "&a/modernshop reload &rpour recharger les &aconfigurations &rdu plugin."
    # A text which appears when the message is hovered.
    show-text: "&bClique pour exécuter"
    # The background color of the usage. Does not affect other specified colors.
    # Click on this link to see all the available colors: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
    color: "WHITE"
  # Message sent when a player executes the command but he doesn't have the permission 'modernshop.commands.shops'.
  no-permission: "&7>> &cVous n'avez pas la permission d'utiliser cette commande."
  # Message sent when all configurations have been reloaded successfully.
  reloaded: "&2>> &rLes configurations du plugin ont été &arechargées&r."

##########################################################
###                     MESSAGES                       ###
##########################################################

# This section groups the messages sent when a player is trying to create a shop.
shop-creation-messages:
  # Message sent when a player doesn't have the permission to create a specific shop type.
  no-permission: "&7>> &cVous n'avez pas la permission de créer ce type de shop."
  # Message sent when the sign isn't placed on a wall.
  not-a-wall-sign: "&7>> &cLa pancarte n'est pas placée sur un coffre."
  # Message sent when the sign isn't placed on a chest.
  not-placed-on-chest: "&7>> &cSeuls les coffres peuvent être utilisés pour créer un shop."
  # Message sent when the chest on which the sign is placed is a double chest.
  double-chest: "&7>> &cUn shop ne peut être créé que sur un coffre simple."
  # Message sent when the chest on which the sign is placed isn't empty.
  chest-not-empty: "&7>> &cLe coffre sur lequel vous essayez créer un shop n'est pas vide."
  # Message sent when the sign isn't placed on the front face of the chest.
  not-placed-on-front: "&7>> &cLa pancarte doit être placée sur la face avant du coffre."
  # Message sent when a player is trying to create a shop but there is a block above the chest or sign.
  block-above: "&7>> &cIl ne doit pas y avoir de block au-dessus du shop."
  # Message sent when a player has reached the max number of shops he can own.
  shop-limit-reached: "&7>> &cVous avez atteint la limite de shops que vous pouvez créer."
  # Message sent when a player is trying to create a shop that use an item already used by another of his shops.
  item-already-used: "&7>> &cUn de vos shops utilise déjà cet objet."
  # Message sent when an error occurred while creating a shop.
  # Usually, this error is due to a shop data backup problem.
  error: "&7>> &cUn problème est survenu lors de la création de votre shop. Veuillez réessayer."
  # Message sent to a player when he created a shop.
  created: "&2>> &rVous avez &acréé &run nouveau &ashop &r!"

shop-messages:
  # Message sent when a player is trying to delete a shop while he is not the owner.
  # Note: A player who has the permission 'modernshop.shops.delete.bypass' can break admin and player shops.
  cannot-break-shop: "&7>> &cVous ne pouvez pas supprimer ce shop."
  # Message sent when a player he is trying to place a block above a shop.
  # Note: Blocks cannot be placed above shops because they would obstruct the vision on the item floating above the chest.
  place-block-above: "&7>> &cVous ne pouvez pas placer un bloc au-dessus d'un shop."
  # Message sent to a player when he is trying to place liquids like water or lava above a shop.
  place-liquid-above: "&7>> &cVous ne pouvez pas placer d'eau ou de lave au-dessus d'un shop."
  # Message sent to a player when he is trying to create a double chest with the chest of a shop.
  double-chest-creation: "&7>> &cVous ne pouvez pas créer un double coffre à partir d'un coffre de shop."
  # This section contains the messages sent when a shop has been deleted.
  shop-deleted:
    # Message sent when a player has deleted one of his shops.
    self: "&2>> &rVous avez &asupprimé &run de vos shops."
    # Message sent when a player has deleted an admin shop.
    admin: "&2>> &rVous avez &asupprimé &run &aadmin shop&r."
    # Message sent when a player has deleted a shop of another player.
    other: "&2>> &rVous avez &asupprimé &run shop de &a%owner_name%&r."
  # Message sent when a player has cancelled the deletion of a shop.
  deletion-cancelled: "&7>> &cAnnulation de la suppression du shop."
  teleportation:
    self: "&2>> &rVous vous êtes &atéléporté &rà un de vos &ashops&r."
    other: "&2>> &rVous vous êtes &atéléporté &rau shop de &a%owner_name%&r."
    admin: "&2>> &rVous vous êtes &atéléporté &rà un &aadmin shop&r."

# This section groups all general messages of the plugin.
general-messages:
  # Message sent to a player when he opens the item selection menu.
  select-item: "&2>> &rOuverture du menu de &asélection&r."
  # Message sent to a player when he closed an item selection menu without selecting an item.
  item-selection-cancelled: "&7>> &cSélection de l'item annulée."
