name: ModernShop
author: Syrows
version: 0.0.1
depend: ["Vault"]
main: fr.syrows.modernshop.ShopPlugin

commands:
  shops:
    description: "A command used to open the shop menu."
    aliases: ["shop"]
  modernshop:
    description: "A command used to reload the plugin."
    aliases: ["mshop", "ms"]

permissions:
  modernshop.*:
    description: "Give access to all permissions of the plugin."
    default: op
    children:
      modernshop.command.*: true
      modernshop.shops.*: true
      modernshop.teleportation.cooldown.bypass: true
  modernshop.command.*:
    description: "Give access to all the commands of the plugin."
    default: op
    children:
      modernshop.command.modernshop: true
      modernshop.command.shops: true
  modernshop.shops.*:
    description: "Give access to all shop features that need a permission."
    default: op
    children:
      modernshop.shops.create.*: true
      modernshop.shops.delete.bypass: true
  modernshop.shops.create.*:
    description: "Allow a player to create admin and player shops."
    default: op
    children:
      modernshop.shops.create.admin: true
      modernshop.shops.create.player: true
  modernshop.shops.create.admin:
    description: "Allow a player to create an admin shop."
    default: op
  modernshop.shops.create.player:
    description: "Allow a player to create a player shop."
    default: op
  modernshop.command.modernshop:
    description: "Give access to the modernshop command."
    default: op
  modernshop.command.shops:
    description: "Give access to the shops command."
    default: op
  modernshop.shops.delete.bypass:
    description: "Allow a player to delete admin and player shops."
    default: op
  modernshop.teleportation.cooldown.bypass:
    description: "Allow a player to bypass cooldown while teleporting."
    default: op
